### ISSUE TITLE
Ошибка на этапе data_split

### ISSUE THREAD

**Issue by mnrozhkov** [7CD/LearningToRank#2]
```bash
(myvenv) (base) mnrozhkov LearningToRank dev ✗ ❯ python src/pipelines/data_split.py --config=params.yaml
Traceback (most recent call last):
  File "src/pipelines/data_split.py", line 44, in <module>
    data_split(config_path=args.config)
  File "src/pipelines/data_split.py", line 30, in data_split
    save_npz(config['data_split']['train_csr_path'], X_train)
  File "/Users/mnrozhkov/mlrepa_school/mipt/LearningToRank/myvenv/lib/python3.8/site-packages/scipy/sparse/_matrix_io.py", line 70, in save_npz
    np.savez_compressed(file, **arrays_dict)
  File "<__array_function__ internals>", line 5, in savez_compressed
  File "/Users/mnrozhkov/mlrepa_school/mipt/LearningToRank/myvenv/lib/python3.8/site-packages/numpy/lib/npyio.py", line 686, in savez_compressed
    _savez(file, args, kwds, True)
  File "/Users/mnrozhkov/mlrepa_school/mipt/LearningToRank/myvenv/lib/python3.8/site-packages/numpy/lib/npyio.py", line 712, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/Users/mnrozhkov/mlrepa_school/mipt/LearningToRank/myvenv/lib/python3.8/site-packages/numpy/lib/npyio.py", line 112, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/Users/mnrozhkov/opt/anaconda3/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/split/X_train.npz'
```

- в документации не указано, что нужна папка split

**Comment by 7CD** [comment]
Добавлена папка split
